# Generated by Django 5.1.3 on 2025-12-03 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePersona', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=20)),
                ('FechaReserva', models.DateField()),
                ('horaReserva', models.TimeField()),
                ('CantidadPersonas', models.IntegerField()),
                ('Estado', models.CharField(choices=[('RESERVADO', 'reservado'), ('SINRESERVAR', 'sinreservar'), ('COMPLETADAS', 'completada'), ('CANCELADA', 'cancelada'), ('SINASISTENCIA', 'sinasistencia')], default='SINRESERVAR', max_length=30)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('Nmesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sinreservar', to='app1.mesa')),
            ],
        ),
    ]
